//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotInterfaces
{
    [Serializable]
    public class MycobotGripperStatusMsg : Message
    {
        public const string k_RosMessageName = "mycobot_interfaces/MycobotGripperStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool status;

        public MycobotGripperStatusMsg()
        {
            this.status = false;
        }

        public MycobotGripperStatusMsg(bool status)
        {
            this.status = status;
        }

        public static MycobotGripperStatusMsg Deserialize(MessageDeserializer deserializer) => new MycobotGripperStatusMsg(deserializer);

        private MycobotGripperStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "MycobotGripperStatusMsg: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
