//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotInterfaces
{
    [Serializable]
    public class MycobotPumpStatusMsg : Message
    {
        public const string k_RosMessageName = "mycobot_interfaces/MycobotPumpStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool status;
        public sbyte pin1;
        public sbyte pin2;

        public MycobotPumpStatusMsg()
        {
            this.status = false;
            this.pin1 = 0;
            this.pin2 = 0;
        }

        public MycobotPumpStatusMsg(bool status, sbyte pin1, sbyte pin2)
        {
            this.status = status;
            this.pin1 = pin1;
            this.pin2 = pin2;
        }

        public static MycobotPumpStatusMsg Deserialize(MessageDeserializer deserializer) => new MycobotPumpStatusMsg(deserializer);

        private MycobotPumpStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.pin1);
            deserializer.Read(out this.pin2);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.pin1);
            serializer.Write(this.pin2);
        }

        public override string ToString()
        {
            return "MycobotPumpStatusMsg: " +
            "\nstatus: " + status.ToString() +
            "\npin1: " + pin1.ToString() +
            "\npin2: " + pin2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
