//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotInterfaces
{
    [Serializable]
    public class GripperStatusResponse : Message
    {
        public const string k_RosMessageName = "mycobot_interfaces/GripperStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool flag;

        public GripperStatusResponse()
        {
            this.flag = false;
        }

        public GripperStatusResponse(bool flag)
        {
            this.flag = flag;
        }

        public static GripperStatusResponse Deserialize(MessageDeserializer deserializer) => new GripperStatusResponse(deserializer);

        private GripperStatusResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.flag);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.flag);
        }

        public override string ToString()
        {
            return "GripperStatusResponse: " +
            "\nflag: " + flag.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
