//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotInterfaces
{
    [Serializable]
    public class GripperStatusRequest : Message
    {
        public const string k_RosMessageName = "mycobot_interfaces/GripperStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool status;

        public GripperStatusRequest()
        {
            this.status = false;
        }

        public GripperStatusRequest(bool status)
        {
            this.status = status;
        }

        public static GripperStatusRequest Deserialize(MessageDeserializer deserializer) => new GripperStatusRequest(deserializer);

        private GripperStatusRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "GripperStatusRequest: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
